@test "certbot-auto is installed and in the path" {
  which certbot-auto
}

@test "letsencrypt configuration exists" {
  cat /etc/letsencrypt/cli.ini|grep "Generated by Chef"
}

@test "cron job is available and executable" {
  test -x /etc/cron.d/certbot
}
