#!/bin/bash

echo -e "\033[0;31m################################################################\033[0m"
echo -e "\033[0;31m#This Scrip will install nginx and rewrite your default config #\033[0m"
echo -en "Type \"\033[23;1myes\033[0m\" when you're really sure: "

read answer

if [[ $(echo $answer | tr "[A-Z]" "[a-z]") == "yes" ]] ; then

dpkg -l|grep nginx >/dev/null && dpkg -l|grep fcgiwrap >/dev/null \
|| sudo apt-get update;sudo apt-get install -y nginx fcgiwrap
pwd=$(pwd)

sudo tee /etc/nginx/sites-enabled/default >/dev/null <<EOF
server {
        listen 80;
        location / {
        fastcgi_index index.cgi;
        try_files \$uri \$uri/ \$uri.html \$uri.cgi?\$query_string;
        gzip off;
        root ${pwd}/www;
        fastcgi_pass  unix:/var/run/fcgiwrap.socket;
        include /etc/nginx/fastcgi_params;
        fastcgi_param \SCRIPT_FILENAME  \$document_root\$fastcgi_script_name;
                   }
                   location ~* \.(js|jpg|png|css)$ {
                   root ${pwd}/;
                   expires 30d;
                   }
        }  
EOF
test -d www || mkdir www
sudo service nginx restart
fi
