#!/bin/bash 

echo Content-type: text/html
echo ""

## make POST and GET stings 
## as bash variables available
POST=$(</dev/stdin)
eval `echo "${POST}"|tr '&' ';'`
eval `echo "${QUERY_STRING}"|tr '&' ';'`
echo  "<!DOCTYPE html>"
echo  "<html lang=\"en\">"
echo  "<head>"
echo  "<meta charset=\"utf-8\">"
echo  "<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">"
echo  "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">"
echo  "<!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->"
echo  "<meta name=\"description\" content=\"\">"
echo  "<meta name=\"author\" content=\"\">"
echo  "<link rel=\"icon\" href=\"/static/favicon.ico\">"
echo  ""
echo  "<title>Bash on stereoids</title>"
echo  ""
echo  "<!-- Bootstrap core CSS -->"
echo  "<link href=\"/static/css/bootstrap.min.css\" rel=\"stylesheet\">"
echo  ""
echo  "<!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->"
echo  "<link href=\"/static/assets/css/ie10-viewport-bug-workaround.css\" rel=\"stylesheet\">"
echo  ""
echo  "<!-- Custom styles for this template -->"
echo  "<link href=\"jumbotron-narrow.css\" rel=\"stylesheet\">"
echo  ""
echo  "<!-- Just for debugging purposes. Don't actually copy these 2 lines! -->"
echo  "<!--[if lt IE 9]><script src=\"/static/assets/js/ie8-responsive-file-warning.js\"></script><![endif]-->"
echo  "<script src=\"/static/assets/js/ie-emulation-modes-warning.js\"></script>"
echo  ""
echo  "<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->"
echo  "<!--[if lt IE 9]>"
echo  "<script src=\"https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js\"></script>"
echo  "<script src=\"https://oss.maxcdn.com/respond/1.4.2/respond.min.js\"></script>"
echo  "<![endif]-->"
echo  "</head>"
echo  ""
echo  "<body>"
echo  ""
echo  "<div class=\"container\">"
echo  "<div class=\"header clearfix\">"
echo  "<nav>"
echo  "<ul class=\"nav nav-pills pull-right\">"
echo  "<li role=\"presentation\" class=\"active\"><a href=\"#\">Home</a></li>"
echo  "<li role=\"presentation\"><a href=\"#\">About</a></li>"
echo  "<li role=\"presentation\"><a href=\"#\">Contact</a></li>"
echo  "</ul>"
echo  "</nav>"
echo  "<h3 class=\"text-muted\">"
pwd 
echo  "</h3>"
echo  "</div>"
echo  ""
echo  "<div class=\"jumbotron\">"
echo  "<h2>"
uname -a 
echo  "</h2>"
echo  "<p class=\"lead\">"
id 
echo  "</p>"
echo  "<p><a class=\"btn btn-lg btn-success\" href=\"https://github.com/tinoschroeter/bash_on_steroids\" role=\"button\">Sign up today</a></p>"
echo  "</div>"
echo  ""
echo  "<div class=\"row marketing\">"
echo  "<div class=\"col-lg-6\">"
echo  "<h4>df -h</h4>"
echo  "<p>"
df -h|sed 's/$/<br>/' 
echo  "</p>"
echo  ""
echo  "<h4>"
echo "free" 
echo  "</h4>"
echo  "<p>"
free|sed 's/$/<br>/' 
echo  "</p>"
echo  ""
echo  "<h4>Ifconfig</h4>"
echo  "<p>"
ifconfig|sed 's/$/<br>/' 
echo  "</p>"
echo  "</div>"
echo  ""
echo  "<div class=\"col-lg-6\">"
echo  "<h4>Uptime</h4>"
echo  "<p>"
uptime 
echo  "</p>"
echo  ""
echo  "<h4>Subheading</h4>"
echo  "<p>Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Cras mattis consectetur purus sit amet fermentum.</p>"
echo  ""
echo  "<h4>Subheading</h4>"
echo  "<p>Maecenas sed diam eget risus varius blandit sit amet non magna.</p>"
echo  "</div>"
echo  "</div>"
echo  ""
echo  "<footer class=\"footer\">"
echo  "<p>&copy; 2016 Company, Inc.</p>"
echo  "</footer>"
echo  ""
echo  "</div> <!-- /container -->"
echo  ""
echo  ""
echo  "<!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->"
echo  "<script src=\"/static/assets/js/ie10-viewport-bug-workaround.js\"></script>"
echo  "</body>"
echo  "</html>"
